svn revert templates/def/JS/*
svn revert templates/def/src/*
svn revert templates/def/lib/*
svn revert templates/def/nivo-slider/*
svn revert templates/def/JS/swfobject/*
svn revert templates/def/JS/jqplot/*
svn revert templates/def/JS/jquniform/*
svn revert templates/def/JS/scroll/*
svn revert templates/admin/*
svn revert templates/admin/JS/*
svn revert templates/admin/JS/jqplot/*
svn revert templates/admin/db/*
svn revert templates/admin/doctxt/*
svn revert templates/admin/bannet/*
svn revert templates/admin/JS/snow-fall/*
svn revert modules/html/lang/*
svn revert modules/html/plugins/*
svn revert modules/html/*
svn revert modules/html/plugins/EnterParagraphs/*
svn revert modules/html/plugins/InsertSmiley/*
svn revert modules/html/plugins/CSS/*
svn revert modules/html/plugins/ContextMenu/*
svn revert modules/html/plugins/TableOperations/*
svn revert modules/html/popups/*