<?
GLOBAL $_PROJECT, $_DOC;

// region changes

if ($_SERVER['HTTP_HOST'] != 'grandnn.com') {
	unset($_PROJECT['TREE'][5]);
	unset($_PROJECT['TREE'][6]);
	unset($_PROJECT['TREE'][7]);
	unset($_PROJECT['TREE'][8]);
}

?>
<div id="myjquerymenu" class="jquerycssmenu inside">
	<ul>
<!-- <?print_r($_PROJECT['TREE'])?> -->
<?
foreach ($_PROJECT['TREE'] as $key => $val){
	if ($key === '' || !empty($val['hidden'])){continue;}
	if (empty($val['hidden']) && empty($val['nomenu']) && (!$_COOKIE['GEO_NONHOME'] || $val['show_region'])){ // GEO_NONHOME определяется в /local/geo_ip
			# для добавленных внешних ссылок
			$val['path'] = (empty($val['link'])) ? $val['path'] : $val['link'];
			$val['path'] = str_replace('/doctxt/','/', $val['path']);
			$active = ($val['path']=="/lombard/") ? 'class=sel': '';
			$active = (strstr($_SERVER['REQUEST_URI'], $val['path'])) ? 'class=act': $active;
		?>
	<li>
<?php
	if (!empty($val['menunolink'])){
				echo '<a href="javascript:;"  '.$active.'>'.$add.$padding.$val['name'].'</a>';
			}else{
?>
		<a href="<?=$val['path']?>"  <?=$active?>><?=$add.$padding?><?=$val['name']?></a>
<?
	}
	if (is_array($val['next']) && sizeof($val['next']) > 0){
		js_down_show_sub($val, $menu_items);
		echo "</li>";
	}


	}
}
?>
	</ul>
</div>
<?
	
function js_down_show_sub( $tree, $curr, $deep = 1)
{
	$next_tree	=& $tree['next'];
	echo '<ul>';
	$num = 0;	
	foreach ( $next_tree as $val) {
		if ($num == 6 && $deep >= 2){
			echo '<li onclick="$(this).nextAll(\'li\').show(); $(this).hide();"><a href="javascript:;">Показать еще</a>';
		}			
		if (!empty($val['hidden'])) {continue;} //  || ($_CONF['GEO_NONHOME'] || !$val['show_region'])
		
		$val['path'] = (empty($val['link'])) ? $val['path'] : $val['link'];
		$val['path'] = str_replace('/doctxt/','/', $val['path']);
		
		$active = (strstr($_SERVER['REQUEST_URI'], $val['path'])) ? 'class=act': '';
		if($val['name'] == 'Распродажа') $val['name'] = '<span class="gold">'.$val['name'].'</span>';
		if (!empty($val['menunolink'])){
			echo '<li><a href="javascript:;"  '.$active.'>'.Main::short($val['name'], 80).'</a>';
		}else{
			echo '<li '.(($num >=6 && $deep >= 2)?'style="display: none;"':'').'><a href="'.$val['path'].'" '.$active.'>'.Main::short($val['name'], 80).'</a>';
		}
		if (is_array($val['next']) && sizeof($val['next']) > 0){
			$lostdeep = $deep;
			js_down_show_sub($val, $menu_items , ++$deep);
			$deep = $lostdeep;
		}
		echo "</li>";
		$num++;		
	}
	echo '</ul>';

}	
	
	?>
