<?

global $_URLALIAS;


//$_URLALIAS['DATA']['/news/'] = '/doctxt/soderz/novosti/';
//$_URLALIAS['DATA']['/portfolio/'] = '/doctxt/soderz/portfo/';
//$_URLALIAS['DATA']['/about/'] = '/doctxt/soderz/kompan/';
//$_URLALIAS['DATA']['/service/'] = '/doctxt/soderz/uslugi/';
//$_URLALIAS['DATA']['/main/'] = '/doctxt/soderz/';
//
//$_URLALIAS['DATA']['aliases']['/doctxt/soderz/novosti/'] = '/news/';
//$_URLALIAS['DATA']['aliases']['/doctxt/soderz/portfo/'] = '/portfolio/';
//$_URLALIAS['DATA']['aliases']['/doctxt/soderz/'] = '/main/';

// REQUEST /news EXEC /doctxt/soderz/novosti 
//$_URLALIAS['DATA']['urls']['/news/'] = '/doctxt/soderz/novosti/';
//$_URLALIAS['DATA']['urls']['/portfolio/'] = '/doctxt/soderz/portfo/';
//$_URLALIAS['DATA']['urls']['/main/'] = '/doctxt/soderz/';




?>